CREATE:
CREATE TABLE MEMBER(
    MEM_ID INT PRIMARY KEY,
    MEM_FNAME VARCHAR2(50) NOT NULL,
    MEM_LNAME VARCHAR2(50) NOT NULL,
    MEM_IDNO VARCHAR2(50) NOT NULL,
    MEM_PHONE VARCHAR2(15),
    MEM_STATUS VARCHAR2(20) NOT NULL CHECK (MEM_STATUS IN ('Active', 'Inactive'))
);

CREATE TABLE PUBLISHER(
    PUBLISHER_ID INT PRIMARY KEY NOT NULL,
    PUBLISHER_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE PRIMARY_GENRE(
    PRIMARY_GENRE_ID INT PRIMARY KEY,
    PRIMARY_GENRE_NAME VARCHAR2(50)
);

CREATE TABLE BOOK(
    BOOK_ID INT PRIMARY KEY,
    BOOK_TITLE VARCHAR2(100) NOT NULL,
    BOOK_ISBN VARCHAR2(20) NOT NULL,
    PUBLISHER_ID INT,
    BOOK_RELDATE DATE,
    PRIMARY_GENRE_ID INT,
    BOOK_DESCRIPT VARCHAR2(500),
    IN_CIRCULATION CHAR(1 BYTE) CHECK (IN_CIRCULATION IN ('Y', 'N')),
    FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER(PUBLISHER_ID),
    FOREIGN KEY (PRIMARY_GENRE_ID) REFERENCES PRIMARY_GENRE(PRIMARY_GENRE_ID)
);

CREATE TABLE STAFF(
    STAFF_ID INT PRIMARY KEY,
    STAFF_FNAME VARCHAR2(50) NOT NULL,
    STAFF_LNAME VARCHAR2(50) NOT NULL,
    STAFF_IDNO VARCHAR2(50) NOT NULL,
    STAFF_PHONE VARCHAR2(15),
    STAFF_TYPE CHAR(1 BYTE) NOT NULL CHECK (STAFF_TYPE IN ('L', 'T', 'S'))
);
-- Modify TECHNICAL_STAFF table
CREATE TABLE TECHNICAL_STAFF(
    STAFF_ID INT PRIMARY KEY,
    SALARY FLOAT NOT NULL CHECK (SALARY > 0),
    DATA_ALLOWANCE FLOAT NOT NULL,
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

-- Modify SUPPORT_STAFF table
CREATE TABLE SUPPORT_STAFF(
    STAFF_ID INT PRIMARY KEY,
    PAY_PER_HR FLOAT NOT NULL CHECK (PAY_PER_HR > 0),
    HRS_WORKED FLOAT NOT NULL CHECK (HRS_WORKED > 0),
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

-- Modify LIBRARIAN table
CREATE TABLE LIBRARIAN(
    STAFF_ID INT PRIMARY KEY,
    LIB_USERNAME VARCHAR2(50) NOT NULL,
    LIB_PASSWORD VARCHAR2(50) NOT NULL,
    WEEKLY_WAGE FLOAT NOT NULL CHECK (WEEKLY_WAGE > 0),
    IS_ADMIN CHAR(1) NOT NULL CHECK (IS_ADMIN IN ('Y', 'N')),
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

CREATE TABLE RENTAL(
    RENTAL_ID INT PRIMARY KEY,
    MEM_ID INT NOT NULL,
    RENTAL_DATE DATE NOT NULL,
    LIB_ID INT NOT NULL,
    FOREIGN KEY (MEM_ID) REFERENCES MEMBER(MEM_ID),
    FOREIGN KEY (LIB_ID) REFERENCES LIBRARIAN(STAFF_ID)
);

CREATE TABLE BOOK_FEE(
    FEE_NUM INT PRIMARY KEY,
    RENTAL_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    FEE_AMOUNT FLOAT NOT NULL CHECK (FEE_AMOUNT > 0),
    FEE_PAID CHAR(1) NOT NULL CHECK (FEE_PAID IN ('Y', 'N')),
    FOREIGN KEY (RENTAL_ID) REFERENCES RENTAL(RENTAL_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID)
);

CREATE TABLE AUTHOR(
    AUTH_ID INT PRIMARY KEY,
    AUTH_FNAME VARCHAR2(50) NOT NULL,
    AUTH_LNAME VARCHAR2(50) NOT NULL,
    AUTH_INIT CHAR(1) NOT NULL,
    AUTH_DOB DATE
);



CREATE TABLE RENTAL_DETAIL(
    RENTAL_ID INT,
    BOOK_ID INT,
    RENTAL_RETURN_DATE DATE NOT NULL,
    RENTAL_RETURNED CHAR(1) NOT NULL CHECK (RENTAL_RETURNED IN ('Y', 'N')),
    PRIMARY KEY (RENTAL_ID, BOOK_ID),
    FOREIGN KEY (RENTAL_ID) REFERENCES RENTAL(RENTAL_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID)
);

CREATE TABLE RESERVATION(
    MEM_ID INT,
    BOOK_ID INT,
    ReservationDate DATE,
    LIB_ID INT,
    PRIMARY KEY (MEM_ID, BOOK_ID, ReservationDate),
    FOREIGN KEY (MEM_ID) REFERENCES MEMBER(MEM_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID),
    FOREIGN KEY (LIB_ID) REFERENCES LIBRARIAN(STAFF_ID)
);

CREATE TABLE BOOK_AUTHOR(
    BOOK_ID INT NOT NULL,
    AUTH_ID INT NOT NULL,
    PRIMARY KEY (BOOK_ID, AUTH_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID),
    FOREIGN KEY (AUTH_ID) REFERENCES AUTHOR(AUTH_ID)
);

Index:
CREATE INDEX idx_author_name ON AUTHOR(AUTH_FNAME, AUTH_LNAME);

CREATE INDEX idx_book_name_author ON BOOK(BOOK_TITLE, PUBLISHER_ID);

CREATE INDEX idx_genre_name ON PRIMARY_GENRE(PRIMARY_GENRE_NAME);

Sequence 

CREATE SEQUENCE MEMBER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE PUBLISHER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE PRIMARY_GENRE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE BOOK_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE STAFF_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE LIBRARIAN_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE RENTAL_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE BOOK_FEE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE AUTHOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE TECHNICAL_STAFF_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE SUPPORT_STAFF_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE RENTAL_DETAIL_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE RESERVATION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;

CREATE SEQUENCE BOOK_AUTHOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE;


DROP Tables:

DROP TABLE BOOK_AUTHOR;
DROP TABLE RESERVATION;
DROP TABLE RENTAL_DETAIL;
DROP TABLE BOOK_FEE;
DROP TABLE RENTAL;
DROP TABLE SUPPORT_STAFF;
DROP TABLE TECHNICAL_STAFF;
DROP TABLE AUTHOR;
DROP TABLE LIBRARIAN;
DROP TABLE STAFF;
DROP TABLE BOOK;
DROP TABLE PRIMARY_GENRE;
DROP TABLE PUBLISHER;
DROP TABLE MEMBER;

INSERT:
-- Sample data for the MEMBER table
INSERT INTO MEMBER (MEM_ID, MEM_FNAME, MEM_LNAME, MEM_IDNO, MEM_PHONE, MEM_STATUS)
VALUES (MEMBER_SEQ.NEXTVAL, 'John', 'Doe', '1234567890', '555-1234', 'Active');

INSERT INTO MEMBER (MEM_ID, MEM_FNAME, MEM_LNAME, MEM_IDNO, MEM_PHONE, MEM_STATUS)
VALUES (MEMBER_SEQ.NEXTVAL, 'Jane', 'Smith', '0987654321', '555-5678', 'Inactive');

INSERT INTO MEMBER (MEM_ID, MEM_FNAME, MEM_LNAME, MEM_IDNO, MEM_PHONE, MEM_STATUS)
VALUES (MEMBER_SEQ.NEXTVAL, 'Michael', 'Johnson', '5432167890', '555-2468', 'Active');

INSERT INTO MEMBER (MEM_ID, MEM_FNAME, MEM_LNAME, MEM_IDNO, MEM_PHONE, MEM_STATUS)
VALUES (MEMBER_SEQ.NEXTVAL, 'Sarah', 'Williams', '6789054321', '555-7890', 'Active');

INSERT INTO MEMBER (MEM_ID, MEM_FNAME, MEM_LNAME, MEM_IDNO, MEM_PHONE, MEM_STATUS)
VALUES (MEMBER_SEQ.NEXTVAL, 'David', 'Brown', '6789054321', '555-1357', 'Inactive');

-- Sample data for the PUBLISHER table
INSERT INTO PUBLISHER (PUBLISHER_ID, PUBLISHER_NAME)
VALUES (PUBLISHER_SEQ.NEXTVAL, 'Penguin Books');

INSERT INTO PUBLISHER (PUBLISHER_ID, PUBLISHER_NAME)
VALUES (PUBLISHER_SEQ.NEXTVAL, 'HarperCollins');

INSERT INTO PUBLISHER (PUBLISHER_ID, PUBLISHER_NAME)
VALUES (PUBLISHER_SEQ.NEXTVAL, 'Random House');

INSERT INTO PUBLISHER (PUBLISHER_ID, PUBLISHER_NAME)
VALUES (PUBLISHER_SEQ.NEXTVAL, 'Simon and Schuster');

INSERT INTO PUBLISHER (PUBLISHER_ID, PUBLISHER_NAME)
VALUES (PUBLISHER_SEQ.NEXTVAL, 'Macmillan Publishers');

-- Sample data for the PRIMARY_GENRE table
INSERT INTO PRIMARY_GENRE (PRIMARY_GENRE_ID, PRIMARY_GENRE_NAME)
VALUES (PRIMARY_GENRE_SEQ.NEXTVAL, 'Fiction');

INSERT INTO PRIMARY_GENRE (PRIMARY_GENRE_ID, PRIMARY_GENRE_NAME)
VALUES (PRIMARY_GENRE_SEQ.NEXTVAL, 'Mystery');

INSERT INTO PRIMARY_GENRE (PRIMARY_GENRE_ID, PRIMARY_GENRE_NAME)
VALUES (PRIMARY_GENRE_SEQ.NEXTVAL, 'Romance');

INSERT INTO PRIMARY_GENRE (PRIMARY_GENRE_ID, PRIMARY_GENRE_NAME)
VALUES (PRIMARY_GENRE_SEQ.NEXTVAL, 'Science Fiction');

INSERT INTO PRIMARY_GENRE (PRIMARY_GENRE_ID, PRIMARY_GENRE_NAME)
VALUES (PRIMARY_GENRE_SEQ.NEXTVAL, 'Biography');

-- Sample data for the BOOK table
INSERT INTO BOOK (BOOK_ID, BOOK_TITLE, BOOK_ISBN, PUBLISHER_ID, BOOK_RELDATE, PRIMARY_GENRE_ID, BOOK_DESCRIPT, IN_CIRCULATION)
VALUES (BOOK_SEQ.NEXTVAL, 'The Great Gatsby', '9780743273565', 1, TO_DATE('2022-01-15', 'YYYY-MM-DD'), 1, 'A classic novel by F. Scott Fitzgerald.', 'Y');

INSERT INTO BOOK (BOOK_ID, BOOK_TITLE, BOOK_ISBN, PUBLISHER_ID, BOOK_RELDATE, PRIMARY_GENRE_ID, BOOK_DESCRIPT, IN_CIRCULATION)
VALUES (BOOK_SEQ.NEXTVAL, 'Harry Potter and the Sorcerer''s Stone', '9780590353427', 2, TO_DATE('2001-10-01', 'YYYY-MM-DD'), 1, 'The first book in the Harry Potter series.', 'Y');

INSERT INTO BOOK (BOOK_ID, BOOK_TITLE, BOOK_ISBN, PUBLISHER_ID, BOOK_RELDATE, PRIMARY_GENRE_ID, BOOK_DESCRIPT, IN_CIRCULATION)
VALUES (BOOK_SEQ.NEXTVAL, 'Pride and Prejudice', '9780141439518', 3, TO_DATE('1813-01-28', 'YYYY-MM-DD'), 3, 'A classic romance novel by Jane Austen.', 'Y');

INSERT INTO BOOK (BOOK_ID, BOOK_TITLE, BOOK_ISBN, PUBLISHER_ID, BOOK_RELDATE, PRIMARY_GENRE_ID, BOOK_DESCRIPT, IN_CIRCULATION)
VALUES (BOOK_SEQ.NEXTVAL, 'Dune', '9780441172719', 4, TO_DATE('1965-06-01', 'YYYY-MM-DD'), 4, 'A science fiction novel by Frank Herbert.', 'Y');

INSERT INTO BOOK (BOOK_ID, BOOK_TITLE, BOOK_ISBN, PUBLISHER_ID, BOOK_RELDATE, PRIMARY_GENRE_ID, BOOK_DESCRIPT, IN_CIRCULATION)
VALUES (BOOK_SEQ.NEXTVAL, 'Steve Jobs', '9781451648539', 5, TO_DATE('2011-10-24', 'YYYY-MM-DD'), 5, 'A biography of Steve Jobs by Walter Isaacson.', 'Y');

-- Sample data for the AUTHOR table
INSERT INTO AUTHOR (AUTH_ID, AUTH_FNAME, AUTH_LNAME, AUTH_INIT, AUTH_DOB)
VALUES (AUTHOR_SEQ.NEXTVAL, 'J.K.', 'Rowling', 'J', TO_DATE('1965-07-31', 'YYYY-MM-DD'));

INSERT INTO AUTHOR (AUTH_ID, AUTH_FNAME, AUTH_LNAME, AUTH_INIT, AUTH_DOB)
VALUES (AUTHOR_SEQ.NEXTVAL, 'Jane', 'Austen', 'J', TO_DATE('1775-12-16', 'YYYY-MM-DD'));

INSERT INTO AUTHOR (AUTH_ID, AUTH_FNAME, AUTH_LNAME, AUTH_INIT, AUTH_DOB)
VALUES (AUTHOR_SEQ.NEXTVAL, 'Frank', 'Herbert', 'F', TO_DATE('1920-10-08', 'YYYY-MM-DD'));

INSERT INTO AUTHOR (AUTH_ID, AUTH_FNAME, AUTH_LNAME, AUTH_INIT, AUTH_DOB)
VALUES (AUTHOR_SEQ.NEXTVAL, 'Walter', 'Isaacson', 'W', TO_DATE('1952-05-20', 'YYYY-MM-DD'));

INSERT INTO AUTHOR (AUTH_ID, AUTH_FNAME, AUTH_LNAME, AUTH_INIT, AUTH_DOB)
VALUES (AUTHOR_SEQ.NEXTVAL, 'F. Scott', 'Fitzgerald', 'F', TO_DATE('1896-09-24', 'YYYY-MM-DD'));

-- Sample data for the BOOK_AUTHOR table
INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTH_ID)
VALUES (1, 2);

INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTH_ID)
VALUES (2, 1);

INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTH_ID)
VALUES (3, 3);

INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTH_ID)
VALUES (4, 4);

INSERT INTO BOOK_AUTHOR (BOOK_ID, AUTH_ID)
VALUES (5, 5);


–insert staff
--1
INSERT INTO STAFF (STAFF_ID, STAFF_FNAME, STAFF_LNAME, STAFF_IDNO, STAFF_PHONE, STAFF_TYPE)
VALUES (STAFF_SEQ.NEXTVAL, 'John', 'Doe', '1234567890', '123-456-7890', 'L');

INSERT INTO TECHNICAL_STAFF (STAFF_ID, SALARY, DATA_ALLOWANCE)
VALUES (STAFF_SEQ.CURRVAL, 5000.00, 10.0);
--2
INSERT INTO STAFF (STAFF_ID, STAFF_FNAME, STAFF_LNAME, STAFF_IDNO, STAFF_PHONE, STAFF_TYPE)
VALUES (STAFF_SEQ.NEXTVAL, 'Jane', 'Smith', '9876543210', '987-654-3210', 'T');
INSERT INTO TECHNICAL_STAFF (STAFF_ID, SALARY, DATA_ALLOWANCE)
VALUES (STAFF_SEQ.CURRVAL, 4500.00, 8.0);
--3
INSERT INTO STAFF (STAFF_ID, STAFF_FNAME, STAFF_LNAME, STAFF_IDNO, STAFF_PHONE, STAFF_TYPE)
VALUES (STAFF_SEQ.NEXTVAL, 'David', 'Johnson', '5555555555', '555-555-5555', 'S');
INSERT INTO SUPPORT_STAFF (STAFF_ID, PAY_PER_HR, HRS_WORKED)
VALUES (STAFF_SEQ.CURRVAL, 20.00, 40.0);
--4
INSERT INTO STAFF (STAFF_ID, STAFF_FNAME, STAFF_LNAME, STAFF_IDNO, STAFF_PHONE, STAFF_TYPE)
VALUES (STAFF_SEQ.NEXTVAL, 'Sarah', 'Williams', '7777777777', '777-777-7777', 'L');
INSERT INTO SUPPORT_STAFF (STAFF_ID, PAY_PER_HR, HRS_WORKED)
VALUES (STAFF_SEQ.CURRVAL, 20.00, 40.0);
--5
INSERT INTO STAFF (STAFF_ID, STAFF_FNAME, STAFF_LNAME, STAFF_IDNO, STAFF_PHONE, STAFF_TYPE)
VALUES (STAFF_SEQ.NEXTVAL, 'Robert', 'Brown', '8888888888', '888-888-8888', 'T');
INSERT INTO LIBRARIAN (STAFF_ID, LIB_USERNAME, LIB_PASSWORD, WEEKLY_WAGE, IS_ADMIN)
VALUES (STAFF_SEQ.CURRVAL, 'librarian1', 'password123', 1000.00, 'Y');
--6
INSERT INTO STAFF (STAFF_ID, STAFF_FNAME, STAFF_LNAME, STAFF_IDNO, STAFF_PHONE, STAFF_TYPE)
VALUES (STAFF_SEQ.NEXTVAL, 'Emily', 'Jones', '9999999999', '999-999-9999', 'S');
INSERT INTO LIBRARIAN (STAFF_ID, LIB_USERNAME, LIB_PASSWORD, WEEKLY_WAGE, IS_ADMIN)
VALUES (STAFF_SEQ.CURRVAL, 'librarian2', 'password456', 950.00, 'N');

-- Insert sample data into the RENTAL table
INSERT INTO RENTAL (RENTAL_ID, MEM_ID, RENTAL_DATE, LIB_ID)
VALUES (RENTAL_SEQ.NEXTVAL, 1, TO_DATE('2023-05-20', 'YYYY-MM-DD'), 5);

INSERT INTO RENTAL (RENTAL_ID, MEM_ID, RENTAL_DATE, LIB_ID)
VALUES (RENTAL_SEQ.NEXTVAL, 2, TO_DATE('2023-05-21', 'YYYY-MM-DD'), 6);

INSERT INTO RENTAL (RENTAL_ID, MEM_ID, RENTAL_DATE, LIB_ID)
VALUES (RENTAL_SEQ.NEXTVAL, 3, TO_DATE('2023-05-22', 'YYYY-MM-DD'), 5);

INSERT INTO RENTAL (RENTAL_ID, MEM_ID, RENTAL_DATE, LIB_ID)
VALUES (RENTAL_SEQ.NEXTVAL, 4, TO_DATE('2023-05-23', 'YYYY-MM-DD'), 6);

INSERT INTO RENTAL (RENTAL_ID, MEM_ID, RENTAL_DATE, LIB_ID)
VALUES (RENTAL_SEQ.NEXTVAL, 5, TO_DATE('2023-05-24', 'YYYY-MM-DD'), 5);

--Sample 1
INSERT INTO RENTAL_DETAIL (RENTAL_ID, BOOK_ID, RENTAL_RETURN_DATE, RENTAL_RETURNED)
VALUES (6, 1, SYSDATE, 'N');

-- Sample 2
INSERT INTO RENTAL_DETAIL (RENTAL_ID, BOOK_ID, RENTAL_RETURN_DATE, RENTAL_RETURNED)
VALUES (6, 2, SYSDATE, 'Y');

-- Sample 3
INSERT INTO RENTAL_DETAIL (RENTAL_ID, BOOK_ID, RENTAL_RETURN_DATE, RENTAL_RETURNED)
VALUES (7, 3, SYSDATE, 'N');

-- Sample 4
INSERT INTO RENTAL_DETAIL (RENTAL_ID, BOOK_ID, RENTAL_RETURN_DATE, RENTAL_RETURNED)
VALUES (7,4, SYSDATE, 'Y');

-- Sample 5
INSERT INTO RENTAL_DETAIL (RENTAL_ID, BOOK_ID, RENTAL_RETURN_DATE, RENTAL_RETURNED)
VALUES (7,5, SYSDATE, 'N');





INSERT INTO BOOK_FEE (FEE_NUM, RENTAL_ID, BOOK_ID, FEE_AMOUNT, FEE_PAID) VALUES
(BOOK_FEE_SEQ.nextval, 6, 1, 10.99, 'Y');

INSERT INTO BOOK_FEE (FEE_NUM, RENTAL_ID, BOOK_ID, FEE_AMOUNT, FEE_PAID) VALUES
(BOOK_FEE_SEQ.nextval, 7, 3, 5.99, 'N');


INSERT INTO RESERVATION (MEM_ID, BOOK_ID, ReservationDate, LIB_ID) VALUES (1, 1, TO_DATE('2023-05-23', 'YYYY-MM-DD'), 5);
INSERT INTO RESERVATION (MEM_ID, BOOK_ID, ReservationDate, LIB_ID) VALUES (2, 3, TO_DATE('2023-05-23', 'YYYY-MM-DD'), 5);
INSERT INTO RESERVATION (MEM_ID, BOOK_ID, ReservationDate, LIB_ID) VALUES (3, 2, TO_DATE('2023-05-24', 'YYYY-MM-DD'), 5);
INSERT INTO RESERVATION (MEM_ID, BOOK_ID, ReservationDate, LIB_ID) VALUES (4, 5, TO_DATE('2023-05-24', 'YYYY-MM-DD'), 6);
INSERT INTO RESERVATION (MEM_ID, BOOK_ID, ReservationDate, LIB_ID) VALUES (5, 4, TO_DATE('2023-05-25', 'YYYY-MM-DD'), 6);


JOIN:
SELECT B.BOOK_TITLE, A.AUTH_FNAME FROM 
    BOOK B
LEFT JOIN 
    BOOK_AUTHOR BA ON B.BOOK_ID = BA.BOOK_ID
LEFT JOIN 
    AUTHOR A ON BA.AUTH_ID = A.AUTH_ID


REPORTS

SELECT
    B.BOOK_TITLE AS "Title",
    A.AUTH_FNAME || ' ' || A.AUTH_LNAME AS "Author",
    G.PRIMARY_GENRE_NAME AS "Genre",
    P.PUBLISHER_NAME AS "Publisher",
    B.BOOK_ISBN AS "ISBN",
    B.BOOK_RELDATE AS "Date of Publication",
    COUNT(B.BOOK_ID) AS "Total Copies",
    SUM(CASE WHEN RD.RENTAL_RETURNED = 'N' THEN 1 ELSE 0 END) AS "Copies On Loan",
    SUM(CASE WHEN B.IN_CIRCULATION = 'N' THEN 1 ELSE 0 END) AS "Copies Lost"
FROM
    BOOK B
LEFT JOIN
    BOOK_AUTHOR BA ON B.BOOK_ID = BA.BOOK_ID
LEFT JOIN
    AUTHOR A ON BA.AUTH_ID = A.AUTH_ID
LEFT JOIN
    PRIMARY_GENRE G ON B.PRIMARY_GENRE_ID = G.PRIMARY_GENRE_ID
LEFT JOIN
    PUBLISHER P ON B.PUBLISHER_ID = P.PUBLISHER_ID
LEFT JOIN
    RENTAL_DETAIL RD ON B.BOOK_ID = RD.BOOK_ID
GROUP BY
    B.BOOK_TITLE,
    A.AUTH_FNAME,
    A.AUTH_LNAME,
    G.PRIMARY_GENRE_NAME,
    P.PUBLISHER_NAME,
    B.BOOK_ISBN,
    B.BOOK_RELDATE;

-- Outstanding Books
SELECT 
    B.BOOK_TITLE,
    COUNT(RD.BOOK_ID) AS "Outstanding Count"
FROM 
    RENTAL_DETAIL RD
LEFT JOIN
    BOOK B ON RD.BOOK_ID = B.BOOK_ID
WHERE 
    RD.RENTAL_RETURN_DATE < CURRENT_DATE
    AND RD.RENTAL_RETURNED = 'N'
GROUP BY 
    B.BOOK_TITLE
ORDER BY 
    COUNT(RD.BOOK_ID) DESC;



SELECT
    B.BOOK_TITLE,
    COUNT(RD.BOOK_ID) AS "Loan Count"
FROM
    RENTAL_DETAIL RD
LEFT JOIN
    BOOK B ON RD.BOOK_ID = B.BOOK_ID
JOIN
    RENTAL R ON RD.RENTAL_ID = R.RENTAL_ID
WHERE
    R.RENTAL_DATE BETWEEN TO_DATE('2023-01-01', 'YYYY-MM-DD') AND TO_DATE('2023-12-31', 'YYYY-MM-DD')
    AND ROWNUM <=3
GROUP BY
    B.BOOK_TITLE
ORDER BY
    COUNT(RD.BOOK_ID) DESC
;


SELECT BF.FEE_NUM, BF.RENTAL_ID, BF.BOOK_ID, BF.FEE_AMOUNT
FROM BOOK_FEE BF
INNER JOIN RENTAL_DETAIL RD ON BF.RENTAL_ID = RD.RENTAL_ID AND BF.BOOK_ID = RD.BOOK_ID
WHERE BF.FEE_PAID = 'N' AND RD.RENTAL_RETURNED = 'N';



select * from reservation where reservationdate > SYSDATE


?
Views

CREATE VIEW BOOK_DETAILS AS
SELECT B.BOOK_ID, B.BOOK_TITLE, A.AUTH_FNAME || ' ' || A.AUTH_LNAME AS AUTHOR, P.PUBLISHER_NAME, G.PRIMARY_GENRE_NAME
FROM BOOK B
JOIN BOOK_AUTHOR BA ON B.BOOK_ID = BA.BOOK_ID
JOIN AUTHOR A ON BA.AUTH_ID = A.AUTH_ID
JOIN PUBLISHER P ON B.PUBLISHER_ID = P.PUBLISHER_ID
JOIN PRIMARY_GENRE G ON B.PRIMARY_GENRE_ID = G.PRIMARY_GENRE_ID;

CREATE VIEW CURRENT_RENTALS AS
SELECT R.RENTAL_ID, M.MEM_FNAME || ' ' || M.MEM_LNAME AS MEMBER, B.BOOK_TITLE, RD.RENTAL_RETURN_DATE
FROM RENTAL R
JOIN MEMBER M ON R.MEM_ID = M.MEM_ID
JOIN RENTAIL_DETAIL RD ON R.RENTAL_ID = RD.RENTAL_ID
JOIN BOOK B ON RD.BOOK_ID = B.BOOK_ID
WHERE RD.RENTAL_RETURNED = 'N';

CREATE VIEW STAFF_INFORMATION AS
SELECT S.STAFF_ID, S.STAFF_FNAME || ' ' || S.STAFF_LNAME AS STAFF_NAME, S.STAFF_TYPE,
       L.LIB_USERNAME, TS.SALARY, SS.PAY_PER_HR
FROM STAFF S
LEFT JOIN LIBRARIAN L ON S.STAFF_ID = L.STAFF_ID
LEFT JOIN TECHNICAL_STAFF TS ON S.STAFF_ID = TS.STAFF_ID
LEFT JOIN SUPPORT_STAFF SS ON S.STAFF_ID = SS.STAFF_ID;


Miscellaneous 

Select * from BOOK where BOOK_Name LIKE ‘%Keyword%’ or BOOK_ID  LIKE ‘%Keyword%’


SELECT ROUND(salary, 2) AS rounded_salary, TRUNC(salary) AS truncated_salary
FROM TECHNICAL_STAFF;

SELECT FEE_NUM, RENTAL_ID, BOOK_ID, ROUND(FEE_AMOUNT, 1) AS ROUNDED_FEE
FROM BOOK_FEE;

SELECT PRIMARY_GENRE_ID, COUNT(*) AS TOTAL_BOOKS
FROM BOOK
GROUP BY PRIMARY_GENRE_ID;

SELECT BOOK_ID, COUNT(*) AS TOTAL_RENTALS
FROM RENTAL_DETAIL
GROUP BY BOOK_ID
HAVING COUNT(*) < 5;

SELECT MEM_FNAME, MEM_LNAME
FROM MEMBER
WHERE MEM_ID IN (
    SELECT MEM_ID
    FROM RENTAL
    WHERE RENTAL_DATE >= (SELECT MAX(RENTAL_DATE) FROM RENTAL)
);


